From python:3.9-buster

RUN mkdir /bot
# RUN pip install - U pip

COPY ./requirements.txt ./bot/requirements.txt
RUN pip install --no-compile  -r /bot/requirements.txt

ENV PYTHONWARNINGS ignore
ENV PYTHONDONTWRITEBYTECODE=true
ENV PYTHONUNBUFFERED 1
ENV PATH="${PATH}:/root/.local/bin"
ENV PYTHONPATH=.

COPY . /bot/

WORKDIR /bot
CMD ["start_prod.sh"]