# Generated by Django 4.1.1 on 2022-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('asgmtId', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('crsId', models.CharField(max_length=7)),
                ('asgmtName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('crsId', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('crsName', models.CharField(max_length=50)),
                ('meets', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('ftyId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ftyFName', models.CharField(max_length=15)),
                ('ftyLName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stdId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stdFName', models.CharField(max_length=15)),
                ('stdLName', models.CharField(max_length=15)),
                ('stdEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
