# Generated by Django 4.1.1 on 2022-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='crsId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='crsId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='stdId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
