# Generated by Django 4.1.1 on 2022-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assignments_crsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stdPassword',
            field=models.CharField(default="b'$2b$09$ndx1B.Fk0JeIuuu5HFYqHeeoKVd.31I44VBTsuOk4KmpSz.PFXZT.'", max_length=500),
        ),
    ]
