# Generated by Django 4.1.1 on 2022-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_students_stdpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stdToken',
            field=models.CharField(default='', max_length=500),
        ),
    ]
