# Generated by Django 4.1.1 on 2022-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_students_stdtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='courses',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ftyEmail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ftyOffice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ftyPhone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
